### ISSUE TITLE
like 문법에 '%'가 없어도 되나요?

### ISSUE THREAD

**Issue by e-seungho-kr** [wotjd4305/Daou-intern#28]
https://github.com/wotjd4305/Daou-intern/blob/355889d7c2013881d1653102dbdebf2eb0503763/backend/daoumarket/src/main/resources/mappers/item.xml#L88

like에 %를 사용하지 않을거라면, in을 사용하는건 어떨까요?

**Comment by seongmink** [comment]
좋은 의견 감사합니다. in으로 쓰는 것이 나을 것 같습니다.
