### ISSUE TITLE
@PathVariable을 사용하지 않고, @RequestParam를 사용한 이유가 있는건가요?

### ISSUE THREAD

**Issue by e-seungho-kr** [wotjd4305/Daou-intern#29]
https://github.com/wotjd4305/Daou-intern/blob/355889d7c2013881d1653102dbdebf2eb0503763/backend/daoumarket/src/main/java/com/daoumarket/controller/FavoriteController.java#L42

**Comment by uni3621** [comment]
@PathVariable로 사용하고

**Comment by uni3621** [comment]
PathVariable을 사용하려 했는데 잘못 작성한 것 같습니다.
PathVariable로 변경하고 요청 URI를 /favorite/{id}로 변경해서 수정하겠습니다.

**Comment by e-seungho-kr** [comment]
아, 그 위에 methode에도 pathvariable이 있길래 .. 수고하세요
